name: rating_summary
description: Create a summary statistic Widget to display the rating and average rating of a product.
version: 0.0.1
repository: https://github.com/floodoo/rating_summary

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
